payments:
  shards:
    -
      url: jdbc:mysql://127.0.0.1:3307/payments
      username: root
      password: 1
      driverClassName: com.mysql.jdbc.Driver
      weight: 10
    -
      url: jdbc:mysql://127.0.0.1:3308/payments
      username: root
      password: 1
      driverClassName: com.mysql.jdbc.Driver
      weight: 10
    -
      url: jdbc:mysql://127.0.0.1:3309/payments
      username: root
      password: 1
      driverClassName: com.mysql.jdbc.Driver,
      weight: 10